{% set name = "skijumpdesign" %}
{% set version = "1.4.0" %}
{% set sha256 = "25432ca21dbe45580e78c5f22cf5f37a04c52d1d5aaaee5a901a05cfb8a8180f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python
  entry_points:
    - skijumpdesign = skijumpdesign.app:app.run_server

requirements:
  build:
    - pip
    - python >=3.6
    - setuptools >=8.0
  run:
    - cython >=0.28.5
    - dash >=0.22.0
    - dash-core-components
    - dash-html-components
    - dash-table
    - flask >=1.0.2
    - matplotlib-base >=2.2.3
    - numpy >=1.13
    - pandas >=0.24.1
    - plotly >=3.1.1
    - python >=3.6
    - scipy >=1.0
    - setuptools >=8.0
    - sympy >=1.2
    - xlrd >=1.2.0

test:
  imports:
    - skijumpdesign
    - skijumpdesign.functions
    - skijumpdesign.skiers
    - skijumpdesign.surfaces
    - skijumpdesign.trajectories
    - skijumpdesign.utils
  commands:
    - skijumpdesign -h

about:
  home: https://skijumpdesign.info
  dev_url: https://gitlab.com/moorepants/skijumpdesign
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Ski Jump Design and Analysis Tool For Specified Equivalent Fall Height'
  description: |
    A ski jump design and analysis tool for equivalent fall height based on the
    work presented in Levy, Dean, Mont Hubbard, James A. McNeil, and Andrew
    Swedberg.  "A Design Rationale for Safer Terrain Park Jumps That Limit
    Equivalent Fall Height." Sports Engineering 18, no. 4 (December 2015):
    227–39.  https://doi.org/10.1007/s12283-015-0182-6. Includes a library for
    2D skiing simulations and a graphical web application for designing and
    analyzing ski jumps. It is written in Python backed by NumPy, SciPy, SymPy,
    Cython, matplotlib, Pandas, Plotly, and Dash.
extra:
  recipe-maintainers:
    - moorepants
