travis:
  secure:
    BINSTAR_TOKEN: tRf5y9KndMssbNeWqpuEYREkOd13biMLhSXYfDXwhJG4UVjK7XmlFXnmtN8VWXGro47ubGoiR4rMj2jDC/mOnykv6MwMw526tagLQ1NbS7ia6HrNJvwFQyLz0iRvBejRoBw8WakiB3UvU8iT5G6zqL1BH7WtE+EwLuantqJJmFrJKkNlgFapuU4VsybvLTqwhmVqAfipR5feXiP1+rO6jGAwl5mUU8FN/vymKUFPqXyWBfMbBvFR8zkV+SVy5k+29hUQhdGrc+E9EOZfZkbVBDsQ/cMpEgCs1pET7qkxU0U8+8p3btGZtqLldjz8LGYqt8laQtaHR5Y5kE4TTYmgl5ddlh5ZhGJgupnSMOxxOuIES/pN15uFQowRtUNBJ+vflrdDJgCYZB5hIh1pyHRWWlQs9hfng7B7zDNosMw72bEQ2KUNrV+wKV7yLe8MoZcPlk7tTerwta7TUuHv0SX9KbKS4IEcz6QKRyqVP7xsb3FWRwbrJLm+BN0Ob4HapbOZ36tctsaisjAfc1D+JiAQwEhhQBARXW5KuErhFfrk5NhgFH+pBG8M7Cr9E0udRlGeSxvONq3C9Dnbp4LPeWIfhKyd2XLYJuTCz77iFe+mH9z34fxz7ijBvOUcuopGMz5oPdXyKOk/C8WSnBlMB5Z3bm8Sv1LRE+f4GmKoXmBSFfk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
