travis:
  secure:
    BINSTAR_TOKEN: tT1JR5RhNo9xEiHvDWWlBnkg5xRqJ9BM82NPHo5yues+kc5zeBujPAq3RsfbzBNPrR0u6FqKrc/AroMtYcjXgv7n8RwXA4hWSHnJEE+lPmIzfUeX7mWJ1M67rBYvPUz333c4RA+K1ZNPL29p5gdbpdVpNNIrYskHJW2c8jjiyl8rYNa03c9r+LfGxal4wWgOa5Ct6SW5uVb36XcSJzd48rRxa4gGFKyE2aF8mlMjE+PiJan7jafB4WfjvKWY3r34x/+nU+zWqNZD6o8fO5R2ahoeYtCSBllegzxxHj//jXQy59AGHEhbWGdrE7U8H7oEfRuJJERR20rLNKBQonTSLBOXdv8qSClZJitGSpcVtfSVejERbv/vzxKwZS3fwo4mrB1N81bfhFJDJL/Qu0vbwEQvoCOkaYop492bM6WvzugJD2ZVcLHWA7vcD6yTxL+1NRQd+l8Jxy2l1O+MNjmC4eaiiaE4kwogpt/wh4kIWZdJjQDj9LA74xD7PVNVC/Y5NuZ9LvJs1aofUn88yHxdztAS/2l6NlJjKAt/6CT7jKRzuVFd3PFs7f1Foky+RV0GzK9ObFpGb0CZVUofDauGAURfpXlssFDwa6+RAYau1OBZwUCTCVS4B4tAaaaqnKBCp5WItAZblc8FbhYQIgByhcSYVc06zz6zVGMUMk1PzFs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
