travis:
  secure:
    BINSTAR_TOKEN: bcaAAuNfl8G7l5CG0e046uIW+47Yv8kCmBZLP2UhxGs6ezc3EKojJBRF/VaVUBDt1JKLHVn+Hyf9O2sQn6zwaFZly8yh/HNqg/u9cAMotwPnljcPHJVHOpBejC8/Q873qX841YW5+cS9tw7g5L/agJlSsuxAtTs9xvLL0kRsweEHTrx2Mm7PoYaf6TJXleCjOmY8tR0ouYt5v8gji/SwSYpoOWjZ9IfQYT3d8yBf+Kfgu2d5Vd0iAvfwz0eUpITLDCdDWkfDRt8qbG78dVS/60dZ57AJLe7IkYxp/25glB7B/mKJtbw8h6qBhDCVVtMM3Hx3GeQ77eBypua6acM/Tm1bJyoEJmzneHk4V9YtqybTauTidvqUF0QwWbNm5vCC61bXLzhSBNOVSeWNC9LBYxBDmfeUUH+1+tRJnJNOfvyxGntTbPJnKadnv9MIJyjrU0qmhm2enS4xhSPNQzfSd50g8nPrgWOr/95hJxQ1IStee/YKayF4PN+RbyQfjGsCc7JFVbCCNxTFVbd6/Rwc8NwhWlS+e1bquYgoDVpWGI+JsAhJ0LV9ghiILc5S4jk3/kRo9EP2xok8Y3NitUwJpYqdUNiAkZETBB188XlJnKOLpB90nPPAbqg+ZdZvr9ionNyBp/vMHxkM8C0w/bvnqQMusir61gM9EIZwOoz3oDo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
