travis:
  secure:
    BINSTAR_TOKEN: FFRFyVTTNoN0YWzWzSAR++MiNYUTSazCEqUsZLWQV+wnn3TjqdiEwKuJZdZRiV4PWmHGOWLG1OX7vIV7k6UxQOb22lahTnM5xW0ojxQu5OvXsoi1ZIHhxy4aPTaGpXXvvuGt8LNugwlH6QuUBMeYUXIIww/5CzD2pKmG3n40E07dHSzjb49iOer/6i5msVYMPmxW3iDiizghFStdKZUhysISDnoQioOMGCCQuxwxMnhqLmNgJbfIy8v5qG8lfIFaSbEHxzvDybJ6XGDgPtxQH5a/f5yC7AkWmDcxYISXwemygo4d7GHbozy+dTyNb2OggGwi7XMgBgt/juUM2Xl7/00jhxqs1NfB8UxSYLeZpUnKzSQNH2XQ4d8PUzg2TZkkDg0+rL6VP75RBXZd4JvCnfn11YZzsMCfo7q63RZa/1zs9Bxkf9K6wjIga3gU2RsSSd74vaP0SXG8Hi1kePM4BKXorOIHZZ1xi3/oM7Atz+sNF0vW887/iVsvCYic2kFtUKl3Hgqp2rg+pxMaZJqh/Sc0fsptjIuSK7I96AU29N/0uw6RxuZpbbtHFF06gwU1gknL4Mv1JMwsgUT0xTzNcimGe6MbLpwufc8GKjXrICcfao0U9bqJdVxYWnKkF0cOn2HpUioTgmUudAONOQFl84PSry4pDABHhNc5320ZH2s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
